const cartActionTypes = {
  TOGGLE_CART_DROPDOWN: 'TOGGLE_CART_DROPDOWN',
  ADD_ITEM: 'ADD_ITEM',
  REDUCE_ITEM: 'REDUCE_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  EMPTY_CART: 'EMPTY_CART',
  SET_CART_FROM_FIREBASE: 'SET_CART_FROM_FIREBASE',
  UPDATE_CART_IN_FIREBASE: 'UPDATE_CART_IN_FIREBASE',
};

export default cartActionTypes;
