const cartActionTypes = {
  TOGGLE_CART_DROPDOWN: 'TOGGLE_CART_DROPDOWN',
  ADD_ITEM: 'ADD_ITEM',
  REDUCE_ITEM: 'REDUCE_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  EMPTY_CART: 'EMPTY_CART',
};

export default cartActionTypes;
